#include "shell.h"

/**
 * error_handler - handles the error messages generated by 
 *                the shell program
 * @ptr: pointer to ShellVar struct
 * @err_num: error number
 * Return: error number
 */
int error_handler(ShellVar *ptr, int err_num)
{
	char *err;

	switch (err_num)
	{
		case -1:
			err = generr_env(ptr);
			break;
		case 2:
			if (sh_strcmp("exit", ptr->parsedArguments[0]) == 0)
				err = generr_exit_shell(ptr);
			else if (sh_strcmp("cd", ptr->parsedArguments[0]) == 0)
				err = generr_cd(ptr);
			break;
		case 126:
			err = generr_permissions(ptr);
			break;
		case 127:
			err = generr_cmd_notfound(ptr);
			break;
		default:
			break;
	}
	
	if (err)
	{
		dprintf(STDERR_FILENO, "%s", err);
		free(err);
	}
	ptr->exit_code = err_num;
	return (err_num);
}
